### ISSUE TITLE
Doesn't compile on SUSE (11 SP1 x86_64)

### ISSUE THREAD

**Issue by soichih** [kashif/node-cuda#6]
node-cuda doesn't seem to compile on our cluster.

```
hayashis@aprun2:~/git/node-cuda> node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.1
gyp info using node@0.10.29 | linux | x64
gyp info spawn python
gyp info spawn args [ '/N/hd00/hayashis/BigRed2/node-v0.10.29-linux-x64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/N/hd00/hayashis/BigRed2/git/node-cuda/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/N/hd00/hayashis/BigRed2/node-v0.10.29-linux-x64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/N/u/hayashis/BigRed2/.node-gyp/0.10.29/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/N/u/hayashis/BigRed2/.node-gyp/0.10.29',
gyp info spawn args   '-Dmodule_root_dir=/N/hd00/hayashis/BigRed2/git/node-cuda',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
hayashis@aprun2:~/git/node-cuda> node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.1
gyp info using node@0.10.29 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/N/hd00/hayashis/BigRed2/git/node-cuda/build'
  CXX(target) Release/obj.target/cuda/src/bindings.o
  CXX(target) Release/obj.target/cuda/src/ctx.o
../src/ctx.cpp: In static member function âstatic v8::Handle<v8::Value> NodeCuda::Ctx::GetApiVersion(v8::Local<v8::String>, const v8::AccessorInfo&)â:
../src/ctx.cpp:165: warning: unused variable âerrorâ
../src/bindings.hpp: At global scope:
../src/bindings.hpp:12: warning: âv8::Handle<v8::Value> NodeCuda::GetDriverVersion(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
../src/bindings.hpp:13: warning: âv8::Handle<v8::Value> NodeCuda::GetDeviceCount(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
  CXX(target) Release/obj.target/cuda/src/device.o
../src/bindings.hpp:12: warning: âv8::Handle<v8::Value> NodeCuda::GetDriverVersion(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
../src/bindings.hpp:13: warning: âv8::Handle<v8::Value> NodeCuda::GetDeviceCount(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
  CXX(target) Release/obj.target/cuda/src/function.o
../src/bindings.hpp:12: warning: âv8::Handle<v8::Value> NodeCuda::GetDriverVersion(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
../src/bindings.hpp:13: warning: âv8::Handle<v8::Value> NodeCuda::GetDeviceCount(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
  CXX(target) Release/obj.target/cuda/src/mem.o
../src/bindings.hpp:12: warning: âv8::Handle<v8::Value> NodeCuda::GetDriverVersion(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
../src/bindings.hpp:13: warning: âv8::Handle<v8::Value> NodeCuda::GetDeviceCount(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
  CXX(target) Release/obj.target/cuda/src/module.o
../src/bindings.hpp:12: warning: âv8::Handle<v8::Value> NodeCuda::GetDriverVersion(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
../src/bindings.hpp:13: warning: âv8::Handle<v8::Value> NodeCuda::GetDeviceCount(v8::Local<v8::String>, const v8::AccessorInfo&)â declared âstaticâ but never defined
  SOLINK_MODULE(target) Release/obj.target/cuda.node
flock: ./Release/linker.lock: Unknown error 524
make: *** [Release/obj.target/cuda.node] Error 65
make: Leaving directory `/N/hd00/hayashis/BigRed2/git/node-cuda/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/N/hd00/hayashis/BigRed2/node-v0.10.29-linux-x64/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 2.6.32.59-0.7.1_1.0402.7496-cray_gem_s
gyp ERR! command "node" "/N/u/hayashis/BigRed2/node-v0.10.29-linux-x64/bin/node-gyp" "build"
gyp ERR! cwd /N/hd00/hayashis/BigRed2/git/node-cuda
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
```

**Comment by kashif** [comment]
@soichih it might be related to this problem: TooTallNate/node-gyp#147 which is related to the fact that node-gyp does not work on NFS.... hmmm can you compile it in `tmp/` and try?

**Comment by soichih** [comment]
I've copied everything to /tmp and this time I believe I've past the error point. However, I am now seeing following

make: Entering directory `/tmp/node-cuda/build'
  SOLINK_MODULE(target) Release/obj.target/cuda.node
/usr/lib64/gcc/x86_64-suse-linux/4.3/../../../../x86_64-suse-linux/bin/ld: cannot find -lcuda
collect2: ld returned 1 exit status

I tried to play with binding.gyp to add the library path, but I couldn't get it to work.. I don't actually see libcuda.so in my cudatoolkit lib64 directory by the way.. I see libcudart.so, however.. but I am going to give up on this for now.

Thanks!
